# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.3.5"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "cocoapods"
# gem "cocoapods-spm"
gem "cocoapods-compact-spec"
gem "cocoapods-xcconfig-hooks"
gem "fastlane"
gem 'fastools', :git => 'git@github.com:MichaelLedger/FastlaneTools.git', :branch => 'main'
gem 'cocoapods-packager', :git => 'git@github.com:MichaelLedger/cocoapods-packager.git', :branch => 'master'
